# Generated by Django 5.1.3 on 2024-11-11 01:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="diary",
            name="updated_at",
        ),
    ]
